### ISSUE TITLE
Won't this expose admin credentials?

### ISSUE THREAD

**Issue by benjick** [Lucas-Geitner/next-js-swr-firestore-exemple#1]
Looking at the docs for Next.JS it says this:

> For the initial page load, getInitialProps will run on the server only. getInitialProps will then run on the client when navigating to a different route via the next/link component or by using next/router.

Wouldn't this expose your admin credentials on navigation?

Ping https://github.com/nandorojo/swr-firestore/issues/17

**Comment by Lucas-Geitner** [comment]
Hello @benjick ! 

Nextjs hide from client all the getInitialProps functions if they are not used in the client side, 

This is the official exemple of firestore with nextjs where you have the same pattern with database call from getServerSideProps

https://github.com/vercel/next.js/blob/canary/examples/with-firebase/pages/profile/%5Busername%5D.js
